version: '3.8'
services:
  web:
    build: .
    ports:
     - "8000:80"
    volumes:
     - .:/app
    environment:
      - AWS_ACCESS_KEY_ID_DOCKER=${AWS_ACCESS_KEY_ID_DOCKER}
      - AWS_SECRET_ACCESS_KEY_DOCKER=${AWS_SECRET_ACCESS_KEY_DOCKER}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}