version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        AWS_REGION: ${AWS_REGION:-us-east-1}
        STAGE: ${STAGE:-dev}
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
        AWS_ACCOUNT_ID: ${AWS_ACCOUNT_ID}
    ports:
      - "8000:80"
    environment:
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - STAGE=${STAGE:-dev}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_ACCOUNT_ID=${AWS_ACCOUNT_ID}
    volumes:
      # Montar credenciales AWS si existen
      - ~/.aws:/root/.aws:ro
      # Volumen para el modelo (para desarrollo)
      - model_cache:/code/app/model
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  model_cache: